###
# Sample Guardfile block for Guard::MtHaml
#
# :input           ("views/src") set input directory with haml files
# :output          ("views")     set output directory for compiled files
# :environment     ("php")       haml environment
# :extension       (nil)         output file extension, uses environment if nil
# :notifications   (true)        toggle guard notifications
# :compress_output (false)       compress compiled haml files
# :static_files    (false)       compile haml to static html
# :run_at_start    (true)        compile files when guard starts
###
guard :mthaml, :input => "views/src", :output => "views"
